[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Seleção de regras: E (Error), F (Pyflakes), UP (Pyupgrade), B (Bugbear), ANN (Annotations)
select = ["E", "F", "UP", "B", "ANN", "S", "PT"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyright]
include = ["system"]
typeCheckingMode = "strict"
reportMissingTypeStubs = false